################################################################################
# $Id: $
################################################################################
development:
  adapter:  <%= ENV['WORKMAN_DDB_ADAPTER']  || 'mysql' %>
  database: <%= ENV['WORKMAN_DDB_DATABASE'] || 'workman_devel' %>
  username: <%= ENV['WORKMAN_DDB_USERNAME'] || 'root' %>
  password: <%= ENV['WORKMAN_DDB_PASSWORD'] %>
  host:     <%= ENV['WORKMAN_DDB_HOST']     || 'localhost' %>

test:
  adapter:  <%= ENV['WORKMAN_TDB_ADAPTER']  || 'mysql' %>
  database: <%= ENV['WORKMAN_TDB_DATABASE'] || 'workman_test' %>
  username: <%= ENV['WORKMAN_TDB_USERNAME'] || 'root' %>
  password: <%= ENV['WORKMAN_TDB_PASSWORD'] %>
  host:     <%= ENV['WORKMAN_TDB_HOST']     || 'localhost' %>

production:
  adapter:  <%= ENV['WORKMAN_PDB_ADAPTER']  || 'mysql' %>
  database: <%= ENV['WORKMAN_PDB_DATABASE'] || 'workman_prod' %>
  username: <%= ENV['WORKMAN_PDB_USERNAME'] || 'root' %>
  password: <%= ENV['WORKMAN_PDB_PASSWORD'] %>
  host:     <%= ENV['WORKMAN_PDB_HOST']     || 'localhost' %>
